name: webview_app_template
description: "A Flutter template project for displaying a web application in a WebView."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.9.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  file_saver: ^0.3.1
  flutter_inappwebview: ^6.1.5
  http: ^1.5.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

# Configuration for flutter_launcher_icons.
flutter_launcher_icons:
  android: true # Generate Android icons.
  ios: true # Generate iOS icons.
  image_path: "assets/icon/app_icon.png" # Path to the main icon source image.
  adaptive_icon_background: "#FFFFFF" # Background color for Android adaptive icons.
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png" # Path for Android adaptive icon foreground.
  remove_alpha_ios: true # Remove alpha channel for iOS icons (recommended).
  # Add min_sdk_android if needed:
  # min_sdk_android: 21 # Minimum SDK version for adaptive icons (default is 21)

# Configuration for flutter_native_splash.
flutter_native_splash:
  # Background color for the splash screen (light mode).
  color: "#FFFFFF"
  # Background color for the splash screen (dark mode).
  color_dark: "#000000" # Example dark mode color
  # Image to display on the splash screen.
  image: assets/icon/splash_logo.png
  # Image for dark mode (optional, uses 'image' if not specified).
  # image_dark: assets/icon/splash_logo_dark.png

  # Enable splash screen generation for platforms.
  android: true
  ios: true
  # web: false # Web splash screen not typically needed for WebView apps

  # Android 12 specific splash screen configuration.
  android_12:
    color: "#FFFFFF" # Background color for Android 12+.
    color_dark: "#000000"
    image: assets/icon/splash_logo.png # Icon for Android 12+.
    # image_dark: assets/icon/splash_logo_dark.png
    # Icon background color (optional, for branding)
    # icon_background_color: "#1976D2"
    # icon_background_color_dark: "#004ba0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
